### PR TITLE
Adding compute manager documentation, with examples

### PR DESCRIPTION
**Pull request by dotsdl**
## Description

This PR adds documentation for setting up and running compute managers,
both in `LocalExecutor` mode and when interfacing with an HPC cluster
scheduler.

## Changelog description

- added compute manager setup documentation

## Status

- [x] Code base linted
- [x] Ready to go

### CODE REVIEW

**Comment by dotsdl** [comment]
@bennybp this is ready for review! Please let me know if I missed anything critical in here!

@peastman here is the doc draft for how to deploy compute managers for HPC: https://github.com/MolSSI/QCFractal/blob/next-docs-compute/docs/source/admin_guide/managers/index.rst#id1

I can't claim that this document doesn't have sharp edges; feedback welcome!

**Comment by bennybp** [comment]
Thanks! This is a good start.

You can do PRs into `main` now. I have a few doc updates though which will go into `next`, then I will do a PR from there with those changes + this PR.

**Comment by peastman** [comment]
Thanks!  I'll try it out today.

**Comment by dotsdl** [comment]
Awesome, thank you @bennybp! I'll make future PRs against `main` by default!

**Pull request merged**
