### PR TITLE
[WIP] Save stub procedure when creating a service

### PR DESCRIPTION
**Pull request by doaa-altarawy**
## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
The service documents have a `output` attribute which can be used as the Procedure stub. This chunk of data is validated, but I think we need to add a status section to it.

**Comment by doaa-altarawy** [comment]
Whenever the service is updated, does this output dict change?
Do we need to keep updating the corresponding procedure whenever we update a service?

**Comment by dgasmith** [comment]
Currently the output dict does not change. Only at the very end. I do think it would be neat however to update the dict every iteration, but if complex we can add this as a TODO.

**Comment by dgasmith** [comment]
So this passes locally, but something is going wrong on Travis. Error:
```
qcfractal/interface/models/torsiondrive.py:159: in <dictcomp>
    procedures = {v._id: v for v in objects}
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <TorsionDrive(id='5c6b6df1f97e560d9f6156a8', success='False', initial_molecule='['5c6b6df1f97e560d9f6156a7']')>
name = '_id'
    @no_type_check
    def __getattr__(self, name):
        try:
            return self.__values__[name]
        except KeyError:
>           raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")
E           AttributeError: 'TorsionDrive' object has no attribute '_id'
```

This is wrong those procedure, id's should _only_ be optimizations and never torsiondrive objects. The logging shows we are not progressing in the torsion drive itself. So compute is going quite wrong:
```
Done True
1 initial tasks pushed to opt_queue
 - - +
Done True
1 initial tasks pushed to opt_queue
 - - +
```

**Comment by doaa-altarawy** [comment]
I got this `_id` error locally with the openff environment.

**Comment by dgasmith** [comment]
Ok, I updated my TorsionDrive and I see the same problem now.

**Pull request merged**
