### PR TITLE
Molecule: Explicitly sets fragment options

### LINKED ISSUE #302: Reaction dataset n-body fragment options
We will change the default behavior of fragmenting Molecules in QCElemental see here: https://github.com/MolSSI/QCElemental/pull/74#discussion_r296754217.

The `Molecule.get_fragment` option should explicitly set options to avoid a breaking change here.

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Closes #302.

## Status
- [ ] Changelog updated
- [x] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
Hmm, still pulling qcelemental 0.4.2 for some reason.

**Comment by Lnaden** [comment]
Because this pin is still in place in the env files:

`  - pydantic>=0.20,<0.30`

And That version of elemental pins `>=0.30.1`

**Comment by dgasmith** [comment]
Good call, fixed.

**Comment by dgasmith** [comment]
@Lnaden Pins fixed here.

**Pull request merged**
