### PR TITLE
Db update

### LINKED ISSUE #33: Database Update Option
Currently, once a database is added from the Client, there is no way to update the database. The `Database.save` member function does have a `force` option that does not currently work. `force` should be fixed, and a test added.

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Allows client Databases to overwrite data on the server. Closes #33.

@dnascimento13 

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
We "overwrite" the database so that the table ID stays the same, but all other data is changed (effectively, a clear and reset).

**Comment by Lnaden** [comment]
Do you think it would be helpful to add a formal reset function of some kind?

**Comment by dgasmith** [comment]
In this context, what are would reset mean?

**Comment by Lnaden** [comment]
Just a thought that if we are going through the process of clear and reset, then would it make sense to provide a formal reset function for the socket? It may also be such a rare thing you would only want to do while also adding a new database that its fine to leave it as is.

**Comment by dgasmith** [comment]
Ah so reset would be delete in this context? Delete is something I haven't formally figure out yet. Somewhere there is a line where it should be possible, but not easy I think.

**Comment by Lnaden** [comment]
> Somewhere there is a line where it should be possible, but not easy I think.

I agree. I think a reason I asked here is this seemed very easy to do, but still has to be intentional. This is fine for now.

> Ah so reset would be delete in this context? 

Yes, sorry. I did mean "delete" instead of "reset"

**Pull request merged**
