### PR TITLE
OpenFF: Fix OpenFFWorkflow class signature

### PR DESCRIPTION
**Pull request by ChayaSt**
## Description
This PR addresses https://github.com/MolSSI/QCFractal/issues/91

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] Changed OpenFFWorkflow class signature to:
```
def __init__(self, name, client=None, **kwargs):
    super().__init__(name, client=client, **kwargs)
```
  - [x] Added `torsiondrive_input` to DataModel which was inadvertently removed with https://github.com/MolSSI/QCFractal/pull/82.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by ChayaSt** [comment]
Yes, I'll add the defaults to this PR. For reference, an example of the structure and defaults is [here](https://github.com/openforcefield/fragmenter/blob/workflow/examples/example_workflow.json)

**Comment by ChayaSt** [comment]
I also see there's a KeyError 
https://travis-ci.org/MolSSI/QCFractal/jobs/449103349#L1168-L1170

There seems to be something weird going on because when I print out what `optimization_meta` [here](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/openffworkflow.py#L198-L200) it's just 2 empty dictionaries:
```
{'optimization_meta': {}, 'qc_meta': {}}
```
but `torsion_meta` does keep the options specified in the workflow JSON and when I print it it has them:
```
{'torsiondrive_meta': {}, 'optimization_meta': {'program': 'geometric', 'coordsys': 'tric'}, 'qc_meta': {'driver': 'gradient', 'method': 'UFF', 'basis': '', 'options': 'none', 'program': 'rdkit'}}
```

**Comment by dgasmith** [comment]
I believe the signature in the tests will need to be changed to:
```
wf = portal.collections.OpenFFWorkflow("Workflow1", client=client, **openff_workflow_options)
```

**Comment by ChayaSt** [comment]
The tests should pass now. 
@Lnaden, I added the default `kwargs`.

**Comment by dgasmith** [comment]
I think this is ready to go.

**Comment by Lnaden** [comment]
I think this is good. Thanks for adding the defaults and better typing to the OpenFFWorkflow, @ChayaSt !

**Pull request merged**
