### PR TITLE
Enable Pydantic v1/v2 dual-compatibility

### PR DESCRIPTION
**Pull request by mattwthompson**
## Description

This is my attempt at taking #736 over the finish line

## Status
- [ ] Code base linted
- [x] Ready to go

closes #736

### CODE REVIEW

**Review by loriab — APPROVED** [review]
lgtm, thanks!

**Comment by loriab** [comment]
I don't have official powers here at qcf, so merge decision/schedule is all @bennybp .

**Comment by mattwthompson** [comment]
My guess is you're thinking of this issue: https://github.com/MolSSI/QCElemental/issues/312

In which case it's still a problem, but under the umbrella of changes required to leverage the v2 API. Since this just allows access to v1 via v2 I think that can still be pushed into the future.

**Comment by bennybp** [comment]
Oh yes, of course :) Thanks for finishing this up!

**Comment by mattwthompson** [comment]
Thank you!

**Pull request merged**
