### PR TITLE
[DNM] CI debug

### PR DESCRIPTION
**Pull request by mattwelborn**

### CODE REVIEW

**Comment by dgasmith** [comment]
Looks like the water hash changed after spare QCElemental Molecule.

**Comment by mattwelborn** [comment]
> Looks like the water hash changed after spare QCElemental Molecule.

Does this mean we need to data-migrate all the hashes in QCA? Are we using these new hashes in production now?

**Comment by dgasmith** [comment]
This isn't an issue with the hash. Its an order of operations issue where the test performs a different rounding + orientation scheme. Of course no hashing is going to be idempotent with respect to repeated canonical orientation and geometry rounding. This isn't a huge deal as it doesn't invalidate our current hashes, but is somewhat concerning for trying to build collisions with respect to old hashes from the same data.

**Comment by dgasmith** [comment]
Handled in #561.

**Pull request closed without merging**
