### PR TITLE
Added LSF to the queue-manager

### LINKED ISSUE #225: Dask-jobqueue add LSFCluster
The `qcfractal-manager` interface is missing the LSFCluster option.

### PR DESCRIPTION
**Pull request by Lnaden**
Fixes #225

I thought I had fixed this previously, was in an experimental branch I had while figuring out dask, whoops.

## Status
- [ ] Changelog updated
- [x] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
Let's also changed the wall time to 6 hours and check the case sensitivity of the cluster keyword?

**Comment by Lnaden** [comment]
> the case sensitivity of the cluster keyword

Which keyword exactly? The `ClusterSettings.scheduler` option? Are you wanting to ensure cast to lower case?

**Comment by dgasmith** [comment]
Exactly.

**Comment by Lnaden** [comment]
Got it, 6 hour default wall clock, scheduler name is now cast to lower case so it should work so long as the user passes in a string

**Pull request merged**
