### PR TITLE
Updated psi4 requirements to 1.3.2 for prod conda envs

### PR DESCRIPTION
**Pull request by dotsdl**
## Description

Updated psi4 requirements to 1.3.2 for prod conda envs

## Changelog description

Updated psi4 requirements to 1.3.2 for prod conda envs

## Status

- [ ] Code base linted
- [ ] Ready to go

### CODE REVIEW

**Comment by bennybp** [comment]
This might require a bit more discussion about what openff really wants from here. 1.3.2 is still fairly old (more than a year), and psi4 official releases are pretty rare.

**Comment by loriab** [comment]
It's good to have v1.3.2 instead of 1.3.0 as minimum, as the latter had a DFT error. But it will have been grabbing 1.3.2 all along since it was released May 2019. If you want current psi with the indefinite hang fix, `psi4/label/dev::psi4 >=1.4a2.dev700,<1.4a2` is probably the string.

**Comment by dotsdl** [comment]
Related: #583

**Comment by dotsdl** [comment]
Closing in favor of #583.

**Pull request closed without merging**
