### PR TITLE
Attempting to run CI with QCEngine 0.21, QCElemental 0.24

### PR DESCRIPTION
**Pull request by dotsdl**
## Status

- [ ] Code base linted
- [ ] Ready to go

### CODE REVIEW

**Comment by dotsdl** [comment]
@bennybp not exactly certain, but in order to use QCEngine 0.21.1, which will include MolSSI/QCEngine#339, I think we'll need to resolve the issues raised by the CI here. Thoughts?

**Comment by bennybp** [comment]
Just a small change needed, and it is now passing. Good to go?

**Comment by bennybp** [comment]
On second thought, maybe we should pin to qcengine >= 0.21 and qcelemental >= 0.24? @loriab says she will be creating a new version of qcengine soon, which wouldn't be pulled in (I think). Or are conda and pip smart enough to pull matching minor versions but different patch levels?

**Comment by dotsdl** [comment]
@bennybp just tried out going with qcengine >= 0.21 and qcelemental >= 0.24; looks like all tests pass!

**Review by bennybp — APPROVED** [review]

**Pull request merged**
